package hibernate;

import javax.persistence.FetchType;
import javax.persistence.OneToMany;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * ItemStore generated by hbm2java
 */
public class ItemStore implements java.io.Serializable {

	private long itemStore;
	private Store store;
	private Item item;
	private Long itemCount;

	public ItemStore() {
	}

	public ItemStore(long itemStore) {
		this.itemStore = itemStore;
	}

	public ItemStore(long itemStore, Store store, Item item, Long itemCount) {
		this.itemStore = itemStore;
		this.store = store;
		this.item = item;
		this.itemCount = itemCount;
	}
	@OneToMany(fetch=FetchType.EAGER)
	public long getItemStore() {
		return this.itemStore;
	}

	public void setItemStore(long itemStore) {
		this.itemStore = itemStore;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Long getItemCount() {
		return this.itemCount;
	}

	public void setItemCount(Long itemCount) {
		this.itemCount = itemCount;
	}

}
