package hibernate;

// default package
// Generated May 12, 2013 3:55:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * ItemType generated by hbm2java
 */
public class ItemType implements java.io.Serializable {

	private long itemType;
	private String typeName;
	private Long itemLevel;
	private Long superTypeFk;

	public ItemType() {
	}

	public ItemType(long itemType) {
		this.itemType = itemType;
	}

	public ItemType(long itemType, String typeName, Long itemLevel,
			Long superTypeFk) {
		this.itemType = itemType;
		this.typeName = typeName;
		this.itemLevel = itemLevel;
		this.superTypeFk = superTypeFk;
	}

	public long getItemType() {
		return this.itemType;
	}

	public void setItemType(long itemType) {
		this.itemType = itemType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Long getItemLevel() {
		return this.itemLevel;
	}

	public void setItemLevel(Long itemLevel) {
		this.itemLevel = itemLevel;
	}

	public Long getSuperTypeFk() {
		return this.superTypeFk;
	}

	public void setSuperTypeFk(Long superTypeFk) {
		this.superTypeFk = superTypeFk;
	}

}
