package hibernate;

// Generated May 16, 2013 2:46:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ItemAttribute generated by hbm2java
 */
public class ItemAttribute implements java.io.Serializable {

	private long itemAttribute;
	private ItemAttributeType itemAttributeType;
	private Item item;
	private String typeName;
	private String valueText;
	private Long valueNumber;
	private Date valueDate;
	private Long dataType;
	private Long orderby;

	public ItemAttribute() {
	}

	public ItemAttribute(long itemAttribute) {
		this.itemAttribute = itemAttribute;
	}

	public ItemAttribute(long itemAttribute,
			ItemAttributeType itemAttributeType, Item item, String typeName,
			String valueText, Long valueNumber, Date valueDate, Long dataType,
			Long orderby) {
		this.itemAttribute = itemAttribute;
		this.itemAttributeType = itemAttributeType;
		this.item = item;
		this.typeName = typeName;
		this.valueText = valueText;
		this.valueNumber = valueNumber;
		this.valueDate = valueDate;
		this.dataType = dataType;
		this.orderby = orderby;
	}

	public long getItemAttribute() {
		return this.itemAttribute;
	}

	public void setItemAttribute(long itemAttribute) {
		this.itemAttribute = itemAttribute;
	}

	public ItemAttributeType getItemAttributeType() {
		return this.itemAttributeType;
	}

	public void setItemAttributeType(ItemAttributeType itemAttributeType) {
		this.itemAttributeType = itemAttributeType;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	public Long getValueNumber() {
		return this.valueNumber;
	}

	public void setValueNumber(Long valueNumber) {
		this.valueNumber = valueNumber;
	}

	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	public Long getDataType() {
		return this.dataType;
	}

	public void setDataType(Long dataType) {
		this.dataType = dataType;
	}

	public Long getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Long orderby) {
		this.orderby = orderby;
	}

}
