package hibernate;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import model.item.dao.HibernateUtil;

import org.hibernate.Query;
import org.hibernate.Session;

/**
 * ItemAction generated by hbm2java
 */
public class ItemAction implements java.io.Serializable {

	private long itemAction;
	private Store storeByStoreFromFk;
	private ItemActionType itemActionType;
	private Store storeByStoreToFk;
	private Item itemFk;
	private Date actionDate;
	private Employee createdBy;
	private Long itemCount;
	private BigDecimal actionPrice;
	private String actionNote;
	private Date created;

	public ItemAction() {
	}

	public ItemAction(long itemAction) {
		this.itemAction = itemAction;
	}

	public ItemAction(long itemAction, Store storeByStoreFromFk,
			ItemActionType itemActionType, Store storeByStoreToFk, Item itemFk,
			Date actionDate, Employee createdBy, Long itemCount,
			BigDecimal actionPrice, String actionNote, Date created) {
		this.itemAction = itemAction;
		this.storeByStoreFromFk = storeByStoreFromFk;
		this.itemActionType = itemActionType;
		this.storeByStoreToFk = storeByStoreToFk;

		this.itemFk = itemFk;
		this.actionDate = actionDate;
		this.createdBy = createdBy;
		this.itemCount = itemCount;
		this.actionPrice = actionPrice;
		this.actionNote = actionNote;
		this.created = created;
	}

	public long getItemAction() {
		return this.itemAction;
	}

	public void setItemAction(long itemAction) {
		this.itemAction = itemAction;
	}

	public Store getStoreByStoreFromFk() {
		return this.storeByStoreFromFk;
	}

	public void setStoreByStoreFromFk(Store storeByStoreFromFk) {
		this.storeByStoreFromFk = storeByStoreFromFk;
	}

	public ItemActionType getItemActionType() {
		return this.itemActionType;
	}

	public void setItemActionType(ItemActionType itemActionType) {
		this.itemActionType = itemActionType;
	}

	public Store getStoreByStoreToFk() {
		return this.storeByStoreToFk;
	}

	public void setStoreByStoreToFk(Store storeByStoreToFk) {
		this.storeByStoreToFk = storeByStoreToFk;
	}

//	public Item getItem() {
//		return this.itemFk;
//	}
//
//	public void setItem(Item itemFk) {
//		this.itemFk = itemFk;
//	}

	public Item getItemFk() {
		return itemFk;
	}

	public void setItemFk(Item itemFk) {
		this.itemFk = itemFk;
	}

	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	public Employee getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}

	public Long getItemCount() {
		return this.itemCount;
	}

	public void setItemCount(Long itemCount) {
		this.itemCount = itemCount;
	}

	public BigDecimal getActionPrice() {
		return this.actionPrice;
	}

	public void setActionPrice(BigDecimal actionPrice) {
		this.actionPrice = actionPrice;
	}

	public String getActionNote() {
		return this.actionNote;
	}

	public void setActionNote(String actionNote) {
		this.actionNote = actionNote;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}
	
	


}
