package hibernate;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ItemAttributeType generated by hbm2java
 */
public class ItemAttributeType implements java.io.Serializable {

	private long itemAttributeType;
	private String typeName;
	private String multipleAttributes;
	private Long dataType;
	private Set typeAttributes = new HashSet(0);
	private Set itemAttributes = new HashSet(0);

	public ItemAttributeType() {
	}

	public ItemAttributeType(long itemAttributeType) {
		this.itemAttributeType = itemAttributeType;
	}

	public ItemAttributeType(long itemAttributeType, String typeName,
			String multipleAttributes, Long dataType, Set typeAttributes,
			Set itemAttributes) {
		this.itemAttributeType = itemAttributeType;
		this.typeName = typeName;
		this.multipleAttributes = multipleAttributes;
		this.dataType = dataType;
		this.typeAttributes = typeAttributes;
		this.itemAttributes = itemAttributes;
	}

	public long getItemAttributeType() {
		return this.itemAttributeType;
	}

	public void setItemAttributeType(long itemAttributeType) {
		this.itemAttributeType = itemAttributeType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getMultipleAttributes() {
		return this.multipleAttributes;
	}

	public void setMultipleAttributes(String multipleAttributes) {
		this.multipleAttributes = multipleAttributes;
	}

	public Long getDataType() {
		return this.dataType;
	}

	public void setDataType(Long dataType) {
		this.dataType = dataType;
	}

	public Set getTypeAttributes() {
		return this.typeAttributes;
	}

	public void setTypeAttributes(Set typeAttributes) {
		this.typeAttributes = typeAttributes;
	}

	public Set getItemAttributes() {
		return this.itemAttributes;
	}

	public void setItemAttributes(Set itemAttributes) {
		this.itemAttributes = itemAttributes;
	}

}
