package hibernate;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemPriceList generated by hbm2java
 */
public class ItemPriceList implements java.io.Serializable {

	private long itemPriceList;
	private PriceList priceList;
	private Item item;
	private Long discountXtra;
	private BigDecimal salePrice;
	private Date created;

	public ItemPriceList() {
	}

	public ItemPriceList(long itemPriceList) {
		this.itemPriceList = itemPriceList;
	}

	public ItemPriceList(long itemPriceList, PriceList priceList, Item item,
			Long discountXtra, BigDecimal salePrice, Date created) {
		this.itemPriceList = itemPriceList;
		this.priceList = priceList;
		this.item = item;
		this.discountXtra = discountXtra;
		this.salePrice = salePrice;
		this.created = created;
	}

	public long getItemPriceList() {
		return this.itemPriceList;
	}

	public void setItemPriceList(long itemPriceList) {
		this.itemPriceList = itemPriceList;
	}

	public PriceList getPriceList() {
		return this.priceList;
	}

	public void setPriceList(PriceList priceList) {
		this.priceList = priceList;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Long getDiscountXtra() {
		return this.discountXtra;
	}

	public void setDiscountXtra(Long discountXtra) {
		this.discountXtra = discountXtra;
	}

	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
