package hibernate;

// default package
// Generated May 12, 2013 3:55:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * ItemStore generated by hbm2java
 */
public class ItemStore implements java.io.Serializable {

	private long itemStore;
	private Long storeFk;
	private Long itemFk;
	private Long itemCount;

	public ItemStore() {
	}

	public ItemStore(long itemStore) {
		this.itemStore = itemStore;
	}

	public ItemStore(long itemStore, Long storeFk, Long itemFk, Long itemCount) {
		this.itemStore = itemStore;
		this.storeFk = storeFk;
		this.itemFk = itemFk;
		this.itemCount = itemCount;
	}

	public long getItemStore() {
		return this.itemStore;
	}

	public void setItemStore(long itemStore) {
		this.itemStore = itemStore;
	}

	public Long getStoreFk() {
		return this.storeFk;
	}

	public void setStoreFk(Long storeFk) {
		this.storeFk = storeFk;
	}

	public Long getItemFk() {
		return this.itemFk;
	}

	public void setItemFk(Long itemFk) {
		this.itemFk = itemFk;
	}

	public Long getItemCount() {
		return this.itemCount;
	}

	public void setItemCount(Long itemCount) {
		this.itemCount = itemCount;
	}

}
