package hibernate;

// Generated May 16, 2013 2:46:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ItemType generated by hbm2java
 */
public class ItemType implements java.io.Serializable {

	private long itemType;
	private ItemType itemType_1;
	private String typeName;
	private Long itemLevel;
	private Set typeAttributes = new HashSet(0);
	private Set itemTypes = new HashSet(0);
	private Set items = new HashSet(0);

	public ItemType() {
	}

	public ItemType(long itemType) {
		this.itemType = itemType;
	}

	public ItemType(long itemType, ItemType itemType_1, String typeName,
			Long itemLevel, Set typeAttributes, Set itemTypes, Set items) {
		this.itemType = itemType;
		this.itemType_1 = itemType_1;
		this.typeName = typeName;
		this.itemLevel = itemLevel;
		this.typeAttributes = typeAttributes;
		this.itemTypes = itemTypes;
		this.items = items;
	}

	public long getItemType() {
		return this.itemType;
	}

	public void setItemType(long itemType) {
		this.itemType = itemType;
	}

	public ItemType getItemType_1() {
		return this.itemType_1;
	}

	public void setItemType_1(ItemType itemType_1) {
		this.itemType_1 = itemType_1;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Long getItemLevel() {
		return this.itemLevel;
	}

	public void setItemLevel(Long itemLevel) {
		this.itemLevel = itemLevel;
	}

	public Set getTypeAttributes() {
		return this.typeAttributes;
	}

	public void setTypeAttributes(Set typeAttributes) {
		this.typeAttributes = typeAttributes;
	}

	public Set getItemTypes() {
		return this.itemTypes;
	}

	public void setItemTypes(Set itemTypes) {
		this.itemTypes = itemTypes;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
