package hibernate;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ItemActionType generated by hbm2java
 */
public class ItemActionType implements java.io.Serializable {

	private long itemActionType;
	private String typeName;
	private Set itemActions = new HashSet(0);

	public ItemActionType() {
	}

	public ItemActionType(long itemActionType) {
		this.itemActionType = itemActionType;
	}

	public ItemActionType(long itemActionType, String typeName, Set itemActions) {
		this.itemActionType = itemActionType;
		this.typeName = typeName;
		this.itemActions = itemActions;
	}

	public long getItemActionType() {
		return this.itemActionType;
	}

	public void setItemActionType(long itemActionType) {
		this.itemActionType = itemActionType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set getItemActions() {
		return this.itemActions;
	}

	public void setItemActions(Set itemActions) {
		this.itemActions = itemActions;
	}

}
