package hibernate;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import model.PriceListM;

/**
 * PriceList generated by hbm2java
 */
public class PriceList implements java.io.Serializable {

	private long priceList;
	private PriceListStatusType priceListStatusType;
	private Long defaultDiscountXtra;
	private Date dateFrom;
	private Date dateTo;
	private String note;
	private Long createdBy;
	private Date created;
	private Long updatedBy;
	private Date updated;
	private Set itemPriceLists = new HashSet(0);
	private Set customerPriceLists = new HashSet(0);

	public PriceList() {
	}

	public PriceList(long priceList) {
		this.priceList = priceList;
	}

	public PriceList(long priceList, PriceListStatusType priceListStatusType,
			Long defaultDiscountXtra, Date dateFrom, Date dateTo, String note,
			Long createdBy, Date created, Long updatedBy, Date updated,
			Set itemPriceLists, Set customerPriceLists) {
		this.priceList = priceList;
		this.priceListStatusType = priceListStatusType;
		this.defaultDiscountXtra = defaultDiscountXtra;
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.note = note;
		this.createdBy = createdBy;
		this.created = created;
		this.updatedBy = updatedBy;
		this.updated = updated;
		this.itemPriceLists = itemPriceLists;
		this.customerPriceLists = customerPriceLists;
	}

	public long getPriceList() {
		return this.priceList;
	}

	public void setPriceList(long priceList) {
		this.priceList = priceList;
	}

	public PriceListStatusType getPriceListStatusType() {
		return this.priceListStatusType;
	}

	public void setPriceListStatusType(PriceListStatusType priceListStatusType) {
		this.priceListStatusType = priceListStatusType;
	}

	public Long getDefaultDiscountXtra() {
		return this.defaultDiscountXtra;
	}

	public void setDefaultDiscountXtra(Long defaultDiscountXtra) {
		this.defaultDiscountXtra = defaultDiscountXtra;
	}

	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Set getItemPriceLists() {
		return this.itemPriceLists;
	}

	public void setItemPriceLists(Set itemPriceLists) {
		this.itemPriceLists = itemPriceLists;
	}

	public Set getCustomerPriceLists() {
		return this.customerPriceLists;
	}

	public void setCustomerPriceLists(Set customerPriceLists) {
		this.customerPriceLists = customerPriceLists;
	}

	 public PriceListM convertToPriceListForm(){
         PriceListM p = new PriceListM();
         SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
         p.setId(""+priceList);
         p.setPriceListStatusType(""+priceListStatusType.getTypeName());
         p.setDefaultDiscountXtra(""+defaultDiscountXtra);
         p.setDateFrom(""+df.format(dateFrom));
         p.setDateTo(""+df.format(dateTo));
         p.setNote(note);
         return p;
 }
}
