package hibernate;

// Generated May 16, 2013 2:46:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private long store;
	private String name;
	private Set itemActionsForStoreToFk = new HashSet(0);
	private Set itemActionsForStoreFromFk = new HashSet(0);
	private Set itemStores = new HashSet(0);

	public Store() {
	}

	public Store(long store) {
		this.store = store;
	}

	public Store(long store, String name, Set itemActionsForStoreToFk,
			Set itemActionsForStoreFromFk, Set itemStores) {
		this.store = store;
		this.name = name;
		this.itemActionsForStoreToFk = itemActionsForStoreToFk;
		this.itemActionsForStoreFromFk = itemActionsForStoreFromFk;
		this.itemStores = itemStores;
	}

	public long getStore() {
		return this.store;
	}

	public void setStore(long store) {
		this.store = store;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItemActionsForStoreToFk() {
		return this.itemActionsForStoreToFk;
	}

	public void setItemActionsForStoreToFk(Set itemActionsForStoreToFk) {
		this.itemActionsForStoreToFk = itemActionsForStoreToFk;
	}

	public Set getItemActionsForStoreFromFk() {
		return this.itemActionsForStoreFromFk;
	}

	public void setItemActionsForStoreFromFk(Set itemActionsForStoreFromFk) {
		this.itemActionsForStoreFromFk = itemActionsForStoreFromFk;
	}

	public Set getItemStores() {
		return this.itemStores;
	}

	public void setItemStores(Set itemStores) {
		this.itemStores = itemStores;
	}

}
