package hibernate;

// Generated May 16, 2013 2:51:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UnitType generated by hbm2java
 */
public class UnitType implements java.io.Serializable {

	private long unitType;
	private String typeName;
	private String longName;
	private Set items = new HashSet(0);

	public UnitType() {
	}

	public UnitType(long unitType) {
		this.unitType = unitType;
	}

	public UnitType(long unitType, String typeName, String longName, Set items) {
		this.unitType = unitType;
		this.typeName = typeName;
		this.longName = longName;
		this.items = items;
	}

	public long getUnitType() {
		return this.unitType;
	}

	public void setUnitType(long unitType) {
		this.unitType = unitType;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getLongName() {
		return this.longName;
	}

	public void setLongName(String longName) {
		this.longName = longName;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
